### ISSUE TITLE
Client - performance tracker

### ISSUE THREAD

**Issue by kasarLaboratory** [KasarLabs/osiris#1]
## Description
Create a script in the format of your choice that runs at the same time as the papyrus client and tracks its performance in real time. Be aware that the format you choose should easily communicate to a database for future usage.

## Instructions
The data to be tracked are the following: 

**System**
- [ ] CPU usage in mo (actual usage/max usage/min usage/ average usage)
- [ ] Think about a chart data model for CPU usage
- [ ]  RAM (memory) usage in mo (actual usage/max usage/min usage/ average usage)
- [ ] Think about a chart data model for RAM (memory) usage
- [ ] Total data received (+ download speeds)
- [ ] Total data sent (+download speeds)
- [ ] Disk usage : data written (write speed)
- [ ] Disk usage : data read (read speed)
- [ ] Temperature tracking

**Client**
- [ ] Health check (up or down)
- [ ] Last synced block
- [ ] Blocks synced / seconds
- [ ] (more soon)

This issue should be easy to implement in any of the 3 clients
